// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/glitaa/stock-exchange/internal/domain (interfaces: BankRepository,WalletRepository,AuditLogRepository,TxManager)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/mocks/repository_mock.go -package=mocks github.com/glitaa/stock-exchange/internal/domain BankRepository,WalletRepository,AuditLogRepository,TxManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/glitaa/stock-exchange/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockBankRepository is a mock of BankRepository interface.
type MockBankRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBankRepositoryMockRecorder
	isgomock struct{}
}

// MockBankRepositoryMockRecorder is the mock recorder for MockBankRepository.
type MockBankRepositoryMockRecorder struct {
	mock *MockBankRepository
}

// NewMockBankRepository creates a new mock instance.
func NewMockBankRepository(ctrl *gomock.Controller) *MockBankRepository {
	mock := &MockBankRepository{ctrl: ctrl}
	mock.recorder = &MockBankRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankRepository) EXPECT() *MockBankRepositoryMockRecorder {
	return m.recorder
}

// GetStockQuantity mocks base method.
func (m *MockBankRepository) GetStockQuantity(ctx context.Context, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockQuantity", ctx, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockQuantity indicates an expected call of GetStockQuantity.
func (mr *MockBankRepositoryMockRecorder) GetStockQuantity(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockQuantity", reflect.TypeOf((*MockBankRepository)(nil).GetStockQuantity), ctx, name)
}

// GetStocks mocks base method.
func (m *MockBankRepository) GetStocks(ctx context.Context) ([]domain.Stock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStocks", ctx)
	ret0, _ := ret[0].([]domain.Stock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStocks indicates an expected call of GetStocks.
func (mr *MockBankRepositoryMockRecorder) GetStocks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStocks", reflect.TypeOf((*MockBankRepository)(nil).GetStocks), ctx)
}

// SetStocks mocks base method.
func (m *MockBankRepository) SetStocks(ctx context.Context, stocks []domain.Stock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStocks", ctx, stocks)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStocks indicates an expected call of SetStocks.
func (mr *MockBankRepositoryMockRecorder) SetStocks(ctx, stocks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStocks", reflect.TypeOf((*MockBankRepository)(nil).SetStocks), ctx, stocks)
}

// UpdateStockQuantity mocks base method.
func (m *MockBankRepository) UpdateStockQuantity(ctx context.Context, name string, delta int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockQuantity", ctx, name, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStockQuantity indicates an expected call of UpdateStockQuantity.
func (mr *MockBankRepositoryMockRecorder) UpdateStockQuantity(ctx, name, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockQuantity", reflect.TypeOf((*MockBankRepository)(nil).UpdateStockQuantity), ctx, name, delta)
}

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
	isgomock struct{}
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockWalletRepository) CreateWallet(ctx context.Context, walletID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, walletID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockWalletRepositoryMockRecorder) CreateWallet(ctx, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockWalletRepository)(nil).CreateWallet), ctx, walletID)
}

// GetStockQuantity mocks base method.
func (m *MockWalletRepository) GetStockQuantity(ctx context.Context, walletID, stockName string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockQuantity", ctx, walletID, stockName)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockQuantity indicates an expected call of GetStockQuantity.
func (mr *MockWalletRepositoryMockRecorder) GetStockQuantity(ctx, walletID, stockName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockQuantity", reflect.TypeOf((*MockWalletRepository)(nil).GetStockQuantity), ctx, walletID, stockName)
}

// GetWallet mocks base method.
func (m *MockWalletRepository) GetWallet(ctx context.Context, walletID string) (domain.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallet", ctx, walletID)
	ret0, _ := ret[0].(domain.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWallet indicates an expected call of GetWallet.
func (mr *MockWalletRepositoryMockRecorder) GetWallet(ctx, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallet", reflect.TypeOf((*MockWalletRepository)(nil).GetWallet), ctx, walletID)
}

// UpdateStockQuantity mocks base method.
func (m *MockWalletRepository) UpdateStockQuantity(ctx context.Context, walletID, stockName string, delta int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStockQuantity", ctx, walletID, stockName, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStockQuantity indicates an expected call of UpdateStockQuantity.
func (mr *MockWalletRepositoryMockRecorder) UpdateStockQuantity(ctx, walletID, stockName, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStockQuantity", reflect.TypeOf((*MockWalletRepository)(nil).UpdateStockQuantity), ctx, walletID, stockName, delta)
}

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAuditLogRepository) Add(ctx context.Context, entry domain.LogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockAuditLogRepositoryMockRecorder) Add(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAuditLogRepository)(nil).Add), ctx, entry)
}

// GetAll mocks base method.
func (m *MockAuditLogRepository) GetAll(ctx context.Context) ([]domain.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]domain.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockAuditLogRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockAuditLogRepository)(nil).GetAll), ctx)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTxManager) RunInTx(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTxManagerMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTxManager)(nil).RunInTx), ctx, fn)
}
